### ISSUE TITLE
Trigger the publish workflow on successful merge of a pull request

### ISSUE THREAD

**Issue by jeffrey-chongsathien** [MixedManagementMethod/mixedmanagementmethod.github.io#9]
At the moment, the `/.github\workflows\publish.yml` file specifies the workflow to trigger:

- manually
- on push to the `main` branch

So, when a pull request merges a development branch to `main`, it doesn't re-publish - it should.

**Comment by jeffrey-chongsathien** [comment]
According to DeepSeek from this prompt:

> How do I trigger a GitHub Action when a pull request is merged to the main branch, or a new commit is made to the main branch?

... this should work.

```
name: CI Build

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build:
    # Only run for merged PRs or direct pushes to main
    if: |
      github.event_name == 'push' || 
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      # Your other steps here
      - name: Run tests
        run: npm test
```
